# yaml-language-server: $schema=https://raw.githubusercontent.com/cawoodm/njinz/master/config.schema.json
global:
  refs:
    errdocs: /etc/injinz/errdocs
    htdocs: /etc/injinz/htdocs
    cache: /etc/injinz/cache
hosts:
  - host: 'http://localhost:8889'
    ruleSets:
      - routes
ruleSets:
  routes:
    mode: any
    rules:
      - when: equals:/pingo
        then:
          static: Pongo!
      - when: /ping
        then:
          static: Pong!
      - when: 'matches:^/ui'
        then:
          static: UI!
      - when: /app1
        then:
          proxy: 'https://github.com/asos-craigmorten/opine-http-proxy'
      - when: /
        then:
          serve: $htdocs
