hosts:
  - host: 'http://localhost:8889'
    ruleSets:
      - routes
ruleSets:
  routes:
    mode: any
    rules:
      - when: /ping
        then:
          static: |-
            Pong!<br>
            You gottit!
      - when: 'regex::^/ui'
        then:
          static: UI!
      - when: 'equals::/pingo'
        then:
          static: Pongo!
      - when: /
        then:
          proxy: 'https://github.com/asos-craigmorten/opine-http-proxy'
