# yaml-language-server: $schema=./config.schema.json
global:
  dirs:
    htdocs: /etc/injinz/htdocs
    errdocs: /etc/injinz/errdocs
    cache: /etc/injinz/cache
  files:
    mimes: /etc/injinz/mimes.yaml
  env:
    - HOSTNAME
  plugins:
    - injinz
hosts:
  - host: 'http://localhost:8889'
    ruleSets:
      - routes
ruleSets:
  routes:
    mode: any
    rules:
      - when: equals:/pingo
        then:
          send: html:Pongo!
      - when: /ping
        then:
          send: Pong!
      - when: 'matches:^/ui'
        then:
          send: text:UI!
      - when: 'matches:^/static'
        then:
          serve:
            root: ./etc/injinz/htdocs
            index: index.html
      # - when: /app1
      #   then:
      #     proxy: 'https://github.com/asos-craigmorten/opine-http-proxy'
      - when: /welcome
        then:
          send: html:<h1>Welcome to INJIN-Z<h1>
      - when: /
        then:
          serve: ./etc/injinz/htdocs
          #TODO: $htdocs
