# yaml-language-server: $schema=https://raw.githubusercontent.com/cawoodm/njinz/master/config.schema.json
global:
  refs:
    errdocs: /etc/injinz/errdocs
    htdocs: /etc/injinz/htdocs
    cache: /etc/injinz/cache
hosts:
  - host: 'http://localhost:8889'
    ruleSets:
      - routes
ruleSets:
  routes:
    mode: any
    rules:
      - when: equals:/pingo
        then:
          fixed: html:Pongo!
      - when: /ping
        then:
          fixed: html:Pong!
      - when: 'matches:^/ui'
        then:
          fixed: html:UI!
      # - when: /app1
      #   then:
      #     proxy: 'https://github.com/asos-craigmorten/opine-http-proxy'
      - when: /
        then:
          static: ./etc/injinz/htdocs
          #TODO: $htdocs
